package com.magistis.millenaire.entity;

import com.magistis.millenaire.Millenaire;
import com.magistis.millenaire.entity.custom.MillVillagerEntity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class MillEntityTypes {

    public static final DeferredRegister<EntityType<?>> ENTITY_TYPES = DeferredRegister.create(ForgeRegistries.ENTITY_TYPES, Millenaire.MOD_ID);

    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_ARTISAN0 = ENTITY_TYPES.register("byzantine_artisan0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_artisan0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_ARTISAN_WIFE0 = ENTITY_TYPES.register("byzantine_artisan_wife0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_artisan_wife0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_BARON0 = ENTITY_TYPES.register("byzantine_baron0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_baron0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_BARON1 = ENTITY_TYPES.register("byzantine_baron1", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_baron1").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_BOY0 = ENTITY_TYPES.register("byzantine_boy0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_boy0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_CENTURIO0 = ENTITY_TYPES.register("byzantine_centurio0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_centurio0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_CENTURIO1 = ENTITY_TYPES.register("byzantine_centurio1", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_centurio1").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_FARMER0 = ENTITY_TYPES.register("byzantine_farmer0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_farmer0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_FARMER1 = ENTITY_TYPES.register("byzantine_farmer1", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_farmer1").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_FARMILLER0 = ENTITY_TYPES.register("byzantine_farmiller0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_farmiller0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_FARMILLER1 = ENTITY_TYPES.register("byzantine_farmiller1", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_farmiller1").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_FRAU0 = ENTITY_TYPES.register("byzantine_frau0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_frau0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_FRAU1 = ENTITY_TYPES.register("byzantine_frau1", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_frau1").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_FRAU2 = ENTITY_TYPES.register("byzantine_frau2", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_frau2").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_FRAU3 = ENTITY_TYPES.register("byzantine_frau3", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_frau3").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_FRAU4 = ENTITY_TYPES.register("byzantine_frau4", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_frau4").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_GIRL0 = ENTITY_TYPES.register("byzantine_girl0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_girl0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_KEEPER0 = ENTITY_TYPES.register("byzantine_keeper0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_keeper0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_KEEPER1 = ENTITY_TYPES.register("byzantine_keeper1", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_keeper1").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_KEEPER2 = ENTITY_TYPES.register("byzantine_keeper2", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_keeper2").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_KEEPER3 = ENTITY_TYPES.register("byzantine_keeper3", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_keeper3").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_LUMBERMAN0 = ENTITY_TYPES.register("byzantine_lumberman0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_lumberman0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_LUMBERMAN1 = ENTITY_TYPES.register("byzantine_lumberman1", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_lumberman1").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_MERCHANT0 = ENTITY_TYPES.register("byzantine_merchant0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_merchant0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_MINER0 = ENTITY_TYPES.register("byzantine_miner0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_miner0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_MINER1 = ENTITY_TYPES.register("byzantine_miner1", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_miner1").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_MINER2 = ENTITY_TYPES.register("byzantine_miner2", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_miner2").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_PAPAS0 = ENTITY_TYPES.register("byzantine_papas0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_papas0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_PAPAS1 = ENTITY_TYPES.register("byzantine_papas1", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_papas1").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_PAPAS2 = ENTITY_TYPES.register("byzantine_papas2", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_papas2").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_PATRIARCH0 = ENTITY_TYPES.register("byzantine_patriarch0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_patriarch0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_RICH_WIFE0 = ENTITY_TYPES.register("byzantine_rich_wife0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_rich_wife0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_SHEPARD0 = ENTITY_TYPES.register("byzantine_shepard0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_shepard0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_SHEPHERD_WIFE0 = ENTITY_TYPES.register("byzantine_shepherd_wife0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_shepherd_wife0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_SILK_SMUGGLER0 = ENTITY_TYPES.register("byzantine_silk_smuggler0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_silk_smuggler0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_SMITH0 = ENTITY_TYPES.register("byzantine_smith0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_smith0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_SMITH1 = ENTITY_TYPES.register("byzantine_smith1", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_smith1").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_SOLDIER0 = ENTITY_TYPES.register("byzantine_soldier0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_soldier0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_WIFE0 = ENTITY_TYPES.register("byzantine_wife0", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_wife0").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_WIFE1 = ENTITY_TYPES.register("byzantine_wife1", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_wife1").toString()));
    public static final RegistryObject<EntityType<MillVillagerEntity>>BYZANTINE_WIFE2 = ENTITY_TYPES.register("byzantine_wife2", () -> EntityType.Builder.<MillVillagerEntity>of(MillVillagerEntity::new, MobCategory.MISC).sized(0.6F, 1.95F).build(new ResourceLocation(Millenaire.MOD_ID, "byzantine_wife2").toString()));

    public static void register(IEventBus eventBus) {
        ENTITY_TYPES.register(eventBus);
    }
}
